[project]
name = 'Tokenized-Retail-Customer-Loyalty-Program'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.partner-exchange]
path = 'contracts/partner-exchange.clar'
clarity_version = 2
epoch = 2.5

[contracts.retailer-verification]
path = 'contracts/retailer-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.reward-issuance]
path = 'contracts/reward-issuance.clar'
clarity_version = 2
epoch = 2.5

[contracts.transaction-tracking]
path = 'contracts/transaction-tracking.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
